### ISSUE TITLE
Add support for gradle platforms

### ISSUE THREAD

**Issue by 0ffz** [NyCodeGHG/gradle-spigot-dependency-loader#1]
Gradle allows you to declare a platform which will suggest dependency versions so you don't need to manually specify them. Currently with these dependencies, the version is not found.

More info: https://docs.gradle.org/current/userguide/java_platform_plugin.html

**Comment by NyCodeGHG** [comment]
Could you share your build script or an example which reproduces the issue?

**Comment by DRSchlaubi** [comment]
I think it doesn't export the version for boms

**Comment by 0ffz** [comment]
Our buildscript is a bit... complicated haha but if you'd like, here's what I'm working with: https://github.com/MineInAbyss/Geary/blob/master/platforms/geary-platform-papermc/build.gradle.kts

The conventions plugins at the top add `implementation(platform("com.mineinabyss:idofront-gradle-platform:${miaConventionsVersion}"))` which can be found here https://github.com/MineInAbyss/Idofront/blob/master/idofront-gradle-platform/build.gradle.kts.

Anything currently using `slim` is what I'd like to move over to be spigot dependencies.

**Comment by NyCodeGHG** [comment]
I think I found and fixed the bug. I also added an [integration test](https://github.com/NyCodeGHG/gradle-spigot-dependency-loader/blob/49a6019d12f45446e750a8cd13cf4f36816dacb0/src/integrationTest/kotlin/BomTest.kt) to make sure this doesn't break

**Comment by NyCodeGHG** [comment]
@0ffz It should work now when you use the latest release.
```kotlin
plugins {
  id("de.nycode.spigot-dependency-loader") version "1.1.0"
}
```

**Comment by 0ffz** [comment]
Can confirm it works, thanks!
