### ISSUE TITLE
Kotlin Multiplatform Libraries not in plugin.yml

### ISSUE THREAD

**Issue by NyCodeGHG** [NyCodeGHG/gradle-spigot-dependency-loader#4]
/cc @DerTev

**Comment by DRSchlaubi** [comment]
I assume this only happens if you use the MPP and not the `-jvm  dependency.

My guess is the mpp dependency gets included, but aether cannot handle that?

**Comment by DRSchlaubi** [comment]
Okay, the issue is, that the MPP module doesn't have any module artifacts, should be fixed in the next version
